public class EvenFibonacci {
    /**
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
     * By starting with 1 and 2, the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     *
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
     * find the sum of the even-valued terms.
     */

    private static long fibEven(int n) {
        long result = 0;
        int[] dp = new int[n + 1];
        dp[0] = 0;
        dp[1] = 1;
        for (int i = 2; i <= n; i++) {
            dp[i] = dp[i - 2] + dp[i - 1];
        }

        for (int num : dp) {
            if (num % 2 == 0) {
                result += num;
                if (result >= 4000000) return result;
            }
        }
        return result;
    }

    public static void main(String[] args) {
        System.out.println(fibEven(50));
    }
}
